## Define Colors Library ##
SC_ColorsLib="./SanityChecker_Colors.conf"


## Configuration ##
SERVICE="httpd"
## SERVICE="$2" # Set as 2nd cmdline args

COLS=$(tput cols)
# Subtract a few characters for the brackets and spacing
## PADDING=$((COLS - ${#SERVICE} - 8)) # Default
PADDING=$((COLS - ${#SERVICE} - 5))

